name: MAIN_PULL_REQUEST

on: pull_request

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create text file
        run: echo "This is some text in the file." > file.txt

      - name: Zip the text file
        run: zip _site.zip file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: ./_site.zip
